
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author willi
 */
public class EtchASketchCanvas extends javax.swing.JPanel {

    private static final int PLAYER_WIDTH = 10;
    private static final int PLAYER_HEIGHT = 10;

    private int canvasWidth;
    private int canvasHeight;

    private int x, y;

    private boolean firstDraw = true;

    /**
     * Creates new form EtchASketch
     */
    public EtchASketchCanvas() {
        initComponents();
        setFocusable(true);
        requestFocusInWindow();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Let superclass do its stuff first

        if (firstDraw) {
            // At the start, draw the player in the center
            initializePlayerLocation();
            firstDraw = false;
        }
        
        // Draw Player
        g.setColor(Color.BLUE);
        g.fillRect(x, y, PLAYER_WIDTH, PLAYER_HEIGHT);
    }

    private void initializePlayerLocation() {
        canvasWidth = this.getWidth();
        canvasHeight = this.getHeight();
        x = canvasWidth / 2 - PLAYER_WIDTH / 2;
        y = canvasHeight / 2 - PLAYER_HEIGHT / 2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("Key Pressed " + evt);
        // TODO 1: on key press, change the x and y coordinate of the player
        // Hint: get the type of key event, and only move the player if arrow keys are presed
        // Update x and y based on the arrow type
        
        
        // Tell java swing to call paintComponent again
        repaint();
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
